import numpy as np

class AudioMonitor:
    def __init__(
        self, monitored_stream_name: str, delay_seconds: float = 0.1
    ) -> None: ...
    """
    monitored_stream_name: str
    delay_seconds: float = 0.1. now this parameter is not used, and the delay effect 
        is achieved by the internal delay of the virtual sink and the playback sink.
    """
    def run(self) -> None: ...
    def stop(self) -> None: ...
    def get_data(self, n_samples: int) -> np.ndarray: ...
    def queue_length(self) -> int: ...
